print("\nVERSION 0.1\n")
print("COMMAND      | OUTPUT")
print("help         | Shows this panel")
print("startup      | Reboots the system")
print("home         | Sends to command panel")
print("new          | Creates a new .py file")
print("edit         | Edits the .py file (WIP)")
print("read         | Read the contents of the .py file")
print("delete       | Deletes the .py file")
print("shutdown     | Shuts down the system (WIP)")
print("clear        | Clears the screen")
print("autorun      | Runs the autorun file")
print("[filename]   | Runs the .py file with this name")
#print("filesystem   | Shows all files")
print("")
